#!/usr/bin/env python3
#
# This examines the single-level WAD files given on the command line and
# adjusts their REJECT lumps to have the same length. This works because
# we use zeroed REJECTs (they are purely an engine optimization); the
# levels can therefore share the same REJECT lump, but wadptr will only
# merge them if the lengths also match.

from omg import *
import sys

levels = {}
largest = None

for filename in sys.argv[1:]:
    inwad = WAD()
    inwad.from_file(filename)
    if len(inwad.maps) != 1:
        continue
    mapname = inwad.maps.keys()[0]
    edit = MapEditor(inwad.maps[mapname])
    reject = edit.reject
    if reject.data != b'\x00' * len(reject.data):
        print("%s %s has non-zero REJECT" % (filename, mapname))
    levels[(filename, mapname)] = edit
    if largest is None or len(largest.data) < len(reject.data):
        largest = reject

for (filename, mapname), edit in levels.items():
    edit.reject = largest
    outwad = WAD()
    outwad.maps[mapname] = edit.to_lumps()
    outwad.to_file(filename)
