name: Makefile CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -q install dosbox deutex
    - name: Find Git version
      id: version
      run: |
        if git describe --exact-match --tags >/dev/null; then
          VERSION=$(git describe --exact-match --tags)
          VERSION=${VERSION/#squashware-/}
        else
          VERSION=$(git rev-parse --short HEAD)
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Build WAD
      run: |
        ./build.sh
        mkdir artifacts-wad
        cp newdoom1.wad artifacts-wad
    - name: Upload WAD
      uses: actions/upload-artifact@v1
      with:
        path: "artifacts-wad"
        name: squashware-${{steps.version.outputs.VERSION}}
    - name: Build DOOF
      run: |
        cd doof
        make
        mkdir artifacts-doof
        cp doof.img artifacts-doof
    - name: Upload DOOF disk image
      uses: actions/upload-artifact@v1
      with:
        path: "doof/artifacts-doof"
        name: doof-${{steps.version.outputs.VERSION}}
