name: Makefile CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -q install dosbox deutex jlha-utils chocolate-doom
    - name: Find Git version
      id: version
      run: |
        if git describe --exact-match --tags >/dev/null; then
          VERSION=$(git describe --exact-match --tags)
          VERSION=${VERSION/#squashware-/}
        else
          VERSION=$(git rev-parse --short HEAD)
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Build wadptr
      run: |
        git clone https://github.com/fragglet/wadptr.git
        cd wadptr
        make -j5
    - name: Build WAD
      run: |
        PATH="$PWD/wadptr:$PATH" ./build.sh
        mkdir artifacts-wad
        cp newdoom1.wad artifacts-wad
    - name: Check demo sync
      run: |
        cd playthru
        make -j5 check
    - name: Upload WAD
      uses: actions/upload-artifact@v1
      with:
        path: "artifacts-wad"
        name: squashware-${{steps.version.outputs.VERSION}}
    - name: Build DOOF
      timeout-minutes: 5
      run: |
        cd doof
        make
        mkdir artifacts-doof
        cp doof.img artifacts-doof
    - name: Test DOOF install
      timeout-minutes: 5
      run: |
        cd doof
        make check
    - name: Upload DOOF disk image
      uses: actions/upload-artifact@v1
      with:
        path: "doof/artifacts-doof"
        name: doof-${{steps.version.outputs.VERSION}}
